export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const GET_INVOICES = 'GET_INVOICES';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';

export const GET_INVOICE_ITEMS = 'GET_INVOICE_ITEMS';
export const CREATE_INVOICE_ITEMS = 'CREATE_INVOICE_ITEMS';
export const EDIT_INVOICE_ITEMS = 'EDIT_INVOICE_ITEMS';
export const DELETE_INVOICE_ITEMS = 'DELETE_INVOICE_ITEMS';